global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: receiver
    metrics_path: /metrics
    static_configs:
      - targets: [ 'receiver:9000' ]
  - job_name: dispatcher
    metrics_path: /metrics
    static_configs:
      - targets: [ 'dispatcher:9000' ]
  - job_name: persister
    metrics_path: /metrics
    static_configs:
      - targets: [ 'persister:9000' ]
  - job_name: consumer
    metrics_path: /metrics
    static_configs:
      - targets: [ 'consumer:9000' ]